include $(APPDIR)/Make.defs

MODULE    = $(CONFIG_ROCKETALT_CONF)
PRIORITY  = $(CONFIG_ROCKETALT_CONF_PRIORITY)
STACKSIZE = $(CONFIG_ROCKETALT_CONF_STACKSIZE)
PROGNAME  = config

# Source files

MAINSRC  = config_main.c

include $(APPDIR)/Application.mk
